version: "3"

services:
  app:
    build: .
    command: sh -c "npm run typeorm migration:run && npm run dev"
    restart: always
    depends_on:
      - mysql
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    env_file:
      - .env.dist
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: apirestful
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3306"